In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("gplay.csv")
df

,Unnamed: 0,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone
1,1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone
2,2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone
3,3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen
4,4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone
...,...,...,...,...,...,...,...,...,...,...
10836,10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone
10837,10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone
10838,10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone
10839,10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+
10840,10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      10841 non-null  int64
 1   App             10841 non-null  object
 2   Category        10841 non-null  object
 3   Rating          9367 non-null   float64
 4   Reviews         10841 non-null  object
 5   Size            10841 non-null  object
 6   Installs        10841 non-null  object
 7   Type            10840 non-null  object
 8   Price           10841 non-null  object
 9   Content Rating  10840 non-null  object
dtypes: float64(1), int64(1), object(8)
memory usage: 847.1+ KB

In [5]:
df.columns

Index(['Unnamed: 0', 'App', 'Category', 'Rating', 'Reviews', 'Size',
       'Installs', 'Type', 'Price', 'Content Rating'],
      dtype='object')

In [6]:
#Drop The Unwanted Cols

df.drop("Unnamed: 0",axis=1,inplace=True)

In [7]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone

In [8]:
df.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
dtype: int64

In [9]:
df.describe()

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
dtypes: float64(1), object(8)
memory usage: 762.4+ KB

In [11]:
rm = df["Rating"].mean()

In [12]:
df["Rating"].fillna(rm,inplace=True)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          10841 non-null  float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
dtypes: float64(1), object(8)
memory usage: 762.4+ KB

In [14]:
df.isna().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              1
Price             0
Content Rating    1
dtype: int64

In [15]:
df.dropna(inplace=True)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10839 entries, 0 to 10840
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10839 non-null  object
 1   Category        10839 non-null  object
 2   Rating          10839 non-null  float64
 3   Reviews         10839 non-null  object
 4   Size            10839 non-null  object
 5   Installs        10839 non-null  object
 6   Type            10839 non-null  object
 7   Price           10839 non-null  object
 8   Content Rating  10839 non-null  object
dtypes: float64(1), object(8)
memory usage: 846.8+ KB

In [17]:
df.isna().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
dtype: int64

In [18]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone

In [21]:
df["Reviews"]=df["Reviews"].astype("float")

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10839 entries, 0 to 10840
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10839 non-null  object
 1   Category        10839 non-null  object
 2   Rating          10839 non-null  float64
 3   Reviews         10839 non-null  float64
 4   Size            10839 non-null  object
 5   Installs        10839 non-null  object
 6   Type            10839 non-null  object
 7   Price           10839 non-null  object
 8   Content Rating  10839 non-null  object
dtypes: float64(2), object(7)
memory usage: 846.8+ KB

In [23]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,19M,"10,000+",Free,0,Everyone
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,14M,"500,000+",Free,0,Everyone
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510.0,8.7M,"5,000,000+",Free,0,Everyone
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,25M,"50,000,000+",Free,0,Teen
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,2.8M,"100,000+",Free,0,Everyone

In [25]:
df["Size"].value_counts()

Varies with device    1694
11M                    198
12M                    196
14M                    194
13M                    191
                      ...
430k                     1
429k                     1
200k                     1
460k                     1
619k                     1
Name: Size, Length: 461, dtype: int64

In [30]:
import numpy as np

In [31]:
def clean_size(x):
    if "k" in x:
        x=x.replace("k","")
        return float(x)/1024
    elif "M" in x:
        x=x.replace("M","")
        return float(x)
    
    elif "Varies with device" in x:
        return np.nan
    
    else:
        return float(x)

In [32]:
df["Size"]=df["Size"].map(clean_size)

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10839 entries, 0 to 10840
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10839 non-null  object
 1   Category        10839 non-null  object
 2   Rating          10839 non-null  float64
 3   Reviews         10839 non-null  float64
 4   Size            9145 non-null   float64
 5   Installs        10839 non-null  object
 6   Type            10839 non-null  object
 7   Price           10839 non-null  object
 8   Content Rating  10839 non-null  object
dtypes: float64(3), object(6)
memory usage: 846.8+ KB

In [34]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,19.0,"10,000+",Free,0,Everyone
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,14.0,"500,000+",Free,0,Everyone
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510.0,8.7,"5,000,000+",Free,0,Everyone
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,25.0,"50,000,000+",Free,0,Teen
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,2.8,"100,000+",Free,0,Everyone

In [35]:
df.isnull().sum()

App                  0
Category             0
Rating               0
Reviews              0
Size              1694
Installs             0
Type                 0
Price                0
Content Rating       0
dtype: int64

In [36]:
1694/10839

0.15628748039487037

In [37]:
sm = df["Size"].mean()

In [38]:
df["Size"].fillna(sm,inplace=True)

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10839 entries, 0 to 10840
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10839 non-null  object
 1   Category        10839 non-null  object
 2   Rating          10839 non-null  float64
 3   Reviews         10839 non-null  float64
 4   Size            10839 non-null  float64
 5   Installs        10839 non-null  object
 6   Type            10839 non-null  object
 7   Price           10839 non-null  object
 8   Content Rating  10839 non-null  object
dtypes: float64(3), object(6)
memory usage: 846.8+ KB

In [40]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,19.0,"10,000+",Free,0,Everyone
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,14.0,"500,000+",Free,0,Everyone
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510.0,8.7,"5,000,000+",Free,0,Everyone
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,25.0,"50,000,000+",Free,0,Teen
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,2.8,"100,000+",Free,0,Everyone

In [41]:
df["Installs"].value_counts()

1,000,000+        1579
10,000,000+       1252
100,000+          1169
10,000+           1054
1,000+             907
5,000,000+         752
100+               719
500,000+           539
50,000+            479
5,000+             477
100,000,000+       409
10+                386
500+               330
50,000,000+        289
50+                205
5+                  82
500,000,000+        72
1+                  67
1,000,000,000+      58
0+                  14
Name: Installs, dtype: int64

In [44]:
df["Installs"]=df["Installs"].str.replace("+","")

C:\Users\admin\AppData\Local\Temp\ipykernel_9592\304575038.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df["Installs"]=df["Installs"].str.replace("+","")

In [45]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Install
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,19.0,"10,000",Free,0,Everyone,"10,000"
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,14.0,"500,000",Free,0,Everyone,"500,000"
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510.0,8.7,"5,000,000",Free,0,Everyone,"5,000,000"
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,25.0,"50,000,000",Free,0,Teen,"50,000,000"
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,2.8,"100,000",Free,0,Everyone,"100,000"

In [46]:
df["Installs"].value_counts()

1,000,000        1579
10,000,000       1252
100,000          1169
10,000           1054
1,000             907
5,000,000         752
100               719
500,000           539
50,000            479
5,000             477
100,000,000       409
10                386
500               330
50,000,000        289
50                205
5                  82
500,000,000        72
1                  67
1,000,000,000      58
0                  14
Name: Installs, dtype: int64

In [47]:
df["Installs"]=df["Installs"].str.replace(",","")

In [48]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Install
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,19.0,10000,Free,0,Everyone,"10,000"
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,14.0,500000,Free,0,Everyone,"500,000"
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510.0,8.7,5000000,Free,0,Everyone,"5,000,000"
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,25.0,50000000,Free,0,Teen,"50,000,000"
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,2.8,100000,Free,0,Everyone,"100,000"

In [49]:
df.drop("Install",axis=1,inplace=True)

In [50]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,19.0,10000,Free,0,Everyone
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,14.0,500000,Free,0,Everyone
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510.0,8.7,5000000,Free,0,Everyone
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,25.0,50000000,Free,0,Teen
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,2.8,100000,Free,0,Everyone

In [51]:
df["Type"].value_counts()

Free    10039
Paid      800
Name: Type, dtype: int64

In [52]:
df["Price"].value_counts()

0         10039
$0.99       148
$2.99       129
$1.99        73
$4.99        72
          ...
$19.90        1
$1.75         1
$14.00        1
$4.85         1
$1.04         1
Name: Price, Length: 92, dtype: int64

In [53]:
df["Price"]=df["Price"].str.replace("$","")

C:\Users\admin\AppData\Local\Temp\ipykernel_9592\2278851203.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df["Price"]=df["Price"].str.replace("$","")

In [54]:
df["Price"].value_counts()

0        10039
0.99       148
2.99       129
1.99        73
4.99        72
         ...
19.90        1
1.75         1
14.00        1
4.85         1
1.04         1
Name: Price, Length: 92, dtype: int64

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10839 entries, 0 to 10840
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10839 non-null  object
 1   Category        10839 non-null  object
 2   Rating          10839 non-null  float64
 3   Reviews         10839 non-null  float64
 4   Size            10839 non-null  float64
 5   Installs        10839 non-null  object
 6   Type            10839 non-null  object
 7   Price           10839 non-null  object
 8   Content Rating  10839 non-null  object
dtypes: float64(3), object(6)
memory usage: 846.8+ KB

In [56]:
df["Installs"]=df["Installs"].astype(int)
df["Price"]=df["Price"].astype(float)

In [57]:
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,19.0,10000,Free,0.0,Everyone
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,14.0,500000,Free,0.0,Everyone
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510.0,8.7,5000000,Free,0.0,Everyone
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,25.0,50000000,Free,0.0,Teen
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,2.8,100000,Free,0.0,Everyone

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10839 entries, 0 to 10840
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10839 non-null  object
 1   Category        10839 non-null  object
 2   Rating          10839 non-null  float64
 3   Reviews         10839 non-null  float64
 4   Size            10839 non-null  float64
 5   Installs        10839 non-null  int32
 6   Type            10839 non-null  object
 7   Price           10839 non-null  float64
 8   Content Rating  10839 non-null  object
dtypes: float64(4), int32(1), object(4)
memory usage: 804.5+ KB

In [59]:
#Display Highest Rating
df["Rating"].max()

5.0

In [63]:
df.loc[df["Rating"]==4.0]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
20,Logo Maker - Small Business,ART_AND_DESIGN,4.0,450.0,14.000000,100000,Free,0.0,Everyone
39,How To Color Disney Princess - Coloring Pages,ART_AND_DESIGN,4.0,591.0,9.400000,500000,Free,0.0,Everyone
50,Real Tractor Farming,AUTO_AND_VEHICLES,4.0,1598.0,56.000000,1000000,Free,0.0,Everyone
58,Restart Navigator,AUTO_AND_VEHICLES,4.0,1403.0,0.196289,100000,Free,0.0,Everyone
66,Used Cars Mexico,AUTO_AND_VEHICLES,4.0,190.0,2.500000,50000,Free,0.0,Everyone
...,...,...,...,...,...,...,...,...,...
10802,FR: My Famous Lover,FAMILY,4.0,185.0,28.000000,10000,Free,0.0,Teen
10814,FR: My Secret Pets!,FAMILY,4.0,785.0,31.000000,50000,Free,0.0,Teen
10817,HTC Sense Input - FR,TOOLS,4.0,885.0,8.000000,100000,Free,0.0,Everyone
10826,Frim: get new friends on local chat rooms,SOCIAL,4.0,88486.0,21.516165,5000000,Free,0.0,Mature 17+
10834,FR Calculator,FAMILY,4.0,7.0,2.600000,500,Free,0.0,Everyone

In [64]:
#Display all the records having rating 4.0
#df.loc[df["Rating"]==4.0]
df[df["Rating"]==4.0]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
20,Logo Maker - Small Business,ART_AND_DESIGN,4.0,450.0,14.000000,100000,Free,0.0,Everyone
39,How To Color Disney Princess - Coloring Pages,ART_AND_DESIGN,4.0,591.0,9.400000,500000,Free,0.0,Everyone
50,Real Tractor Farming,AUTO_AND_VEHICLES,4.0,1598.0,56.000000,1000000,Free,0.0,Everyone
58,Restart Navigator,AUTO_AND_VEHICLES,4.0,1403.0,0.196289,100000,Free,0.0,Everyone
66,Used Cars Mexico,AUTO_AND_VEHICLES,4.0,190.0,2.500000,50000,Free,0.0,Everyone
...,...,...,...,...,...,...,...,...,...
10802,FR: My Famous Lover,FAMILY,4.0,185.0,28.000000,10000,Free,0.0,Teen
10814,FR: My Secret Pets!,FAMILY,4.0,785.0,31.000000,50000,Free,0.0,Teen
10817,HTC Sense Input - FR,TOOLS,4.0,885.0,8.000000,100000,Free,0.0,Everyone
10826,Frim: get new friends on local chat rooms,SOCIAL,4.0,88486.0,21.516165,5000000,Free,0.0,Mature 17+
10834,FR Calculator,FAMILY,4.0,7.0,2.600000,500,Free,0.0,Everyone

In [65]:
#Display all record having max rating
df[df["Rating"]==5.0]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
329,Hojiboy Tojiboyev Life Hacks,COMICS,5.0,15.0,37.0,1000,Free,0.0,Everyone
612,American Girls Mobile Numbers,DATING,5.0,5.0,4.4,1000,Free,0.0,Mature 17+
615,Awake Dating,DATING,5.0,2.0,70.0,100,Free,0.0,Mature 17+
633,Spine- The dating app,DATING,5.0,5.0,9.3,500,Free,0.0,Teen
636,Girls Live Talk - Free Text and Video Chat,DATING,5.0,6.0,5.0,100,Free,0.0,Mature 17+
...,...,...,...,...,...,...,...,...,...
10721,Mad Dash Fo' Cash,GAME,5.0,14.0,16.0,100,Free,0.0,Everyone
10742,GKPB FP Online Church,LIFESTYLE,5.0,32.0,7.9,1000,Free,0.0,Everyone
10776,Monster Ride Pro,GAME,5.0,1.0,24.0,10,Free,0.0,Everyone
10820,Fr. Daoud Lamei,FAMILY,5.0,22.0,8.6,1000,Free,0.0,Teen
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4.0,3.6,100,Free,0.0,Everyone

In [67]:
#Display only app name category and rating whose rating values is 5.0

df[["App","Category","Rating"]].loc[df["Rating"]==5.0]

                                              App   Category  Rating
329                  Hojiboy Tojiboyev Life Hacks     COMICS     5.0
612                 American Girls Mobile Numbers     DATING     5.0
615                                  Awake Dating     DATING     5.0
633                         Spine- The dating app     DATING     5.0
636    Girls Live Talk - Free Text and Video Chat     DATING     5.0
...                                           ...        ...     ...
10721                           Mad Dash Fo' Cash       GAME     5.0
10742                       GKPB FP Online Church  LIFESTYLE     5.0
10776                            Monster Ride Pro       GAME     5.0
10820                             Fr. Daoud Lamei     FAMILY     5.0
10837            Fr. Mike Schmitz Audio Teachings     FAMILY     5.0

[274 rows x 3 columns]

In [68]:
df["Type"].value_counts()

Free    10039
Paid      800
Name: Type, dtype: int64

In [69]:
#Display all the Records of Free App

df[df["Price"]==0]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.100000,159.0,19.000000,10000,Free,0.0,Everyone
1,Coloring book moana,ART_AND_DESIGN,3.900000,967.0,14.000000,500000,Free,0.0,Everyone
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.700000,87510.0,8.700000,5000000,Free,0.0,Everyone
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.500000,215644.0,25.000000,50000000,Free,0.0,Teen
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.300000,967.0,2.800000,100000,Free,0.0,Everyone
...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.500000,38.0,53.000000,5000,Free,0.0,Everyone
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.000000,4.0,3.600000,100,Free,0.0,Everyone
10838,Parkinson Exercices FR,MEDICAL,4.193338,3.0,9.500000,1000,Free,0.0,Everyone
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.500000,114.0,21.516165,1000,Free,0.0,Mature 17+
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.500000,398307.0,19.000000,10000000,Free,0.0,Everyone

In [70]:
df[df["Price"]!=0]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
234,TurboScan: scan documents and receipts in PDF,BUSINESS,4.700000,11442.0,6.800000,100000,Paid,4.99,Everyone
235,Tiny Scanner Pro: PDF Doc Scan,BUSINESS,4.800000,10295.0,39.000000,100000,Paid,4.99,Everyone
290,TurboScan: scan documents and receipts in PDF,BUSINESS,4.700000,11442.0,6.800000,100000,Paid,4.99,Everyone
291,Tiny Scanner Pro: PDF Doc Scan,BUSINESS,4.800000,10295.0,39.000000,100000,Paid,4.99,Everyone
427,Puffin Browser Pro,COMMUNICATION,4.000000,18247.0,21.516165,100000,Paid,3.99,Everyone
...,...,...,...,...,...,...,...,...,...
10735,FP VoiceBot,FAMILY,4.193338,17.0,0.153320,100,Paid,0.99,Mature 17+
10760,Fast Tract Diet,HEALTH_AND_FITNESS,4.400000,35.0,2.400000,1000,Paid,7.99,Everyone
10782,Trine 2: Complete Story,GAME,3.800000,252.0,11.000000,10000,Paid,16.99,Teen
10785,"sugar, sugar",FAMILY,4.200000,1405.0,9.500000,10000,Paid,1.20,Everyone
10798,Word Search Tab 1 FR,FAMILY,4.193338,0.0,0.996094,50,Paid,1.04,Everyone

In [71]:
df[df["Type"]=="Free"]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.100000,159.0,19.000000,10000,Free,0.0,Everyone
1,Coloring book moana,ART_AND_DESIGN,3.900000,967.0,14.000000,500000,Free,0.0,Everyone
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.700000,87510.0,8.700000,5000000,Free,0.0,Everyone
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.500000,215644.0,25.000000,50000000,Free,0.0,Teen
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.300000,967.0,2.800000,100000,Free,0.0,Everyone
...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.500000,38.0,53.000000,5000,Free,0.0,Everyone
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.000000,4.0,3.600000,100,Free,0.0,Everyone
10838,Parkinson Exercices FR,MEDICAL,4.193338,3.0,9.500000,1000,Free,0.0,Everyone
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.500000,114.0,21.516165,1000,Free,0.0,Mature 17+
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.500000,398307.0,19.000000,10000000,Free,0.0,Everyone

In [72]:
# Most Expensive App

df["Price"].max()

400.0

In [73]:
df[["Price","App"]].loc[df["Price"]==400.0]

      Price                       App
4367  400.0  I'm Rich - Trump Edition

In [74]:
#Display records whose Rating is between 4 To 5

df[(df["Rating"]>=4.0) & (df["Rating"]<=5.0)]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.100000,159.0,19.000000,10000,Free,0.0,Everyone
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.700000,87510.0,8.700000,5000000,Free,0.0,Everyone
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.500000,215644.0,25.000000,50000000,Free,0.0,Teen
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.300000,967.0,2.800000,100000,Free,0.0,Everyone
5,Paper flowers instructions,ART_AND_DESIGN,4.400000,167.0,5.600000,50000,Free,0.0,Everyone
...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.500000,38.0,53.000000,5000,Free,0.0,Everyone
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.000000,4.0,3.600000,100,Free,0.0,Everyone
10838,Parkinson Exercices FR,MEDICAL,4.193338,3.0,9.500000,1000,Free,0.0,Everyone
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.500000,114.0,21.516165,1000,Free,0.0,Mature 17+
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.500000,398307.0,19.000000,10000000,Free,0.0,Everyone

In [75]:
#Display All Free Apps Having rating of 5.0

df[(df["Type"]=="Free") & (df["Rating"]==5.0)]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
329,Hojiboy Tojiboyev Life Hacks,COMICS,5.0,15.0,37.0,1000,Free,0.0,Everyone
612,American Girls Mobile Numbers,DATING,5.0,5.0,4.4,1000,Free,0.0,Mature 17+
615,Awake Dating,DATING,5.0,2.0,70.0,100,Free,0.0,Mature 17+
633,Spine- The dating app,DATING,5.0,5.0,9.3,500,Free,0.0,Teen
636,Girls Live Talk - Free Text and Video Chat,DATING,5.0,6.0,5.0,100,Free,0.0,Mature 17+
...,...,...,...,...,...,...,...,...,...
10721,Mad Dash Fo' Cash,GAME,5.0,14.0,16.0,100,Free,0.0,Everyone
10742,GKPB FP Online Church,LIFESTYLE,5.0,32.0,7.9,1000,Free,0.0,Everyone
10776,Monster Ride Pro,GAME,5.0,1.0,24.0,10,Free,0.0,Everyone
10820,Fr. Daoud Lamei,FAMILY,5.0,22.0,8.6,1000,Free,0.0,Teen
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4.0,3.6,100,Free,0.0,Everyone

In [78]:
tf=df.loc[df["Type"]=='Paid']

In [80]:
pmin = tf["Rating"].min()
pmin

1.0

In [81]:
tf.loc[tf["Rating"]==pmin]

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating
4127,Speech Therapy: F,FAMILY,1.0,1.0,16.0,10,Paid,2.99,Everyone
5978,Truck Driving Test Class 3 BC,FAMILY,1.0,1.0,2.0,50,Paid,1.49,Everyone